import {
    type RouteConfig,
    index,
    route,
} from "@react-router/dev/routes";

export default [
    index("routes/home.tsx"),
    route("/login", "routes/login.tsx"),
    route("/dashboard", "dashboard/dashboard.tsx"),
    route("/master-data/:entity", "master-data/master-data.tsx"),
    route("/pendaftaran", "pendaftaran/layout.tsx", [
        route("registrasi-baru", "pendaftaran/registrasi-baru/registrasi-baru.tsx"),
        route("registrasi-lama", "pendaftaran/registrasi-lama/registrasi-lama.tsx"),
        route("anjungan-mandiri", "pendaftaran/anjungan-mandiri/anjungan-mandiri.tsx"),
        route("jadwal-dokter", "pendaftaran/jadwal-dokter/jadwal-dokter.tsx"),
        route("pilih-poli", "pendaftaran/pilih-poli/pilih-poli.tsx"),
        route("antrean", "pendaftaran/antrean/antrean.tsx"),
        route("booking", "pendaftaran/booking/booking.tsx"),
        route("validasi-penjamin", "pendaftaran/validasi-penjamin/validasi-penjamin.tsx"),
        route("bridging-bpjs", "pendaftaran/bridging-bpjs/bridging-bpjs.tsx"),
        route("bridging-satusehat", "pendaftaran/bridging-satusehat/bridging-satusehat.tsx"),
        route("riwayat", "pendaftaran/riwayat/riwayat.tsx"),
        route("cetak-dokumen", "pendaftaran/cetak-dokumen/cetak-dokumen.tsx"),
        route("upload-dokumen", "pendaftaran/upload-dokumen/upload-dokumen.tsx"),
        route("mutasi", "pendaftaran/mutasi/mutasi.tsx"),
        route("pembatalan", "pendaftaran/pembatalan/pembatalan.tsx"),
        route("monitoring", "pendaftaran/monitoring/monitoring.tsx"),
        route("audit-log", "pendaftaran/audit-log/audit-log.tsx"),
        route("laporan", "pendaftaran/laporan/laporan.tsx"),
        route("pengaturan", "pendaftaran/pengaturan/pengaturan.tsx"),
    ]),
    route("/jadwal-dokter", "dashboard/jadwal-dokter/jadwal-dokter.tsx"),
    route("/rekam-medis", "rekam-medis/rekam-medis.tsx"),
    route("/pemeriksaan", "pemeriksaan/pemeriksaan.tsx"),
    route("/farmasi", "farmasi/farmasi.tsx"),
    route("/rawat-inap", "rawat-inap/rawat-inap.tsx"),
    route("/laporan", "laporan/laporan.tsx"),
    route("/pengaturan", "pengaturan/pengaturan.tsx"),
] satisfies RouteConfig;
